title: Bayesian analysis hometask blog
description: Homework of Bayesian analysis class. Kliment Ohridski
footer_text: Bayesian analysis
header_feature_image: ../uploads/12.jpg
header_text: My Hometask Blog
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/placeholder3.jpg
favicon: ../uploads/thomas_bayes.gif
gridlayout: false
fixednavbar: false
upzoom: true
